# Generated by Django 2.0.1 on 2020-02-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CooperationAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('sys_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cooperation_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DaogouManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daogou_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiddleAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('super_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'middle_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdinaryAdminRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'ordinary_admin_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('sys_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'super_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysManagerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'sys_manager_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('auth_string', models.CharField(max_length=32)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_manager_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sys_role_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransSysRoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trans_sys_role_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ordinary_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_manager',
                'managed': False,
            },
        ),
    ]
