# Generated by Django 2.0.1 on 2020-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(blank=True, max_length=50, null=True)),
                ('member_level', models.CharField(blank=True, max_length=50, null=True)),
                ('member_score', models.CharField(blank=True, max_length=50, null=True)),
                ('member_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('member_authority', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'member_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('member_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('member_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('member_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'member_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_score', models.CharField(blank=True, max_length=70, null=True)),
                ('member_name', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'member_score',
                'managed': False,
            },
        ),
    ]
