# Generated by Django 2.0.1 on 2020-02-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBoss',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('dz_name', models.CharField(max_length=50)),
                ('is_no', models.IntegerField()),
            ],
            options={
                'db_table': 'd_boss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans_id', models.IntegerField()),
                ('fans_name', models.CharField(max_length=50)),
                ('fans_num', models.IntegerField()),
            ],
            options={
                'db_table': 'd_fans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('user_number', models.IntegerField()),
            ],
            options={
                'db_table': 'd_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DOrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField()),
                ('order_id', models.IntegerField(unique=True)),
                ('d_data', models.TimeField()),
                ('d_class', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('tracking_number', models.CharField(max_length=100)),
                ('z_state', models.IntegerField()),
                ('f_state', models.IntegerField()),
                ('f_jiaoyi', models.IntegerField()),
            ],
            options={
                'db_table': 'd_order_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_number', models.IntegerField()),
                ('d_xiaoshou', models.FloatField()),
                ('d_tuihuo', models.FloatField()),
                ('d_tuihuolv', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'd_performance',
                'managed': False,
            },
        ),
    ]
